# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_userinfo_user_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('mode', models.IntegerField(choices=[(1, '공지사항'), (2, '자유게시판')])),
                ('user_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_info', to='user.UserInfo')),
            ],
        ),
    ]
