# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_board', '0002_auto_20170612_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsboard',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
