# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-09 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_board', '0005_auto_20170708_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsboard',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
