# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news_company', models.CharField(max_length=16)),
                ('xml_address', models.CharField(max_length=255)),
                ('news_section', models.CharField(max_length=16)),
            ],
        ),
    ]
