# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news_company', models.CharField(max_length=16)),
                ('xml_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NewsComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_component.NewsCompany')),
            ],
        ),
        migrations.CreateModel(
            name='NewsSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news_section', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='newscomponent',
            name='news_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_component.NewsSection'),
        ),
    ]
