# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_component', '0002_auto_20170322_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscontent',
            name='news_company',
            field=models.IntegerField(choices=[(1, '조선일보'), (2, '동아일보'), (3, '한겨레'), (4, '중앙일보'), (5, '매일경제'), (6, '경향신문'), (7, '데일리한국'), (8, '스포츠한국'), (9, '한국경제'), (10, '파이낸셜'), (11, '헤럴드'), (12, '국민일보'), (13, '뉴스데일리'), (14, '구글뉴스'), (15, '오마이뉴스'), (16, '노컷뉴스'), (17, '서울경제')]),
        ),
        migrations.AlterField(
            model_name='newscontent',
            name='news_section',
            field=models.IntegerField(choices=[(1, '주요기사'), (2, '인기기사'), (3, '정치'), (4, '경제'), (5, '사회'), (6, '국제'), (7, '문화'), (8, 'IT'), (9, '과학'), (10, '스포츠'), (11, '연예'), (12, '부동산'), (13, '금융'), (14, '생활'), (15, '건강'), (16, '교육'), (17, '도서'), (18, '여성'), (19, '여행'), (20, '게임'), (21, '미디어'), (22, '오피니언')]),
        ),
    ]
